export enum TechTags {
    HTML = "assets/icons/HTML5.svg",
    CSS = "assets/icons/CSS3.svg",
    SCSS = "assets/icons/Sass.svg",
    TailwindCSS = "assets/icons/Tailwind_CSS.svg",
    JAVASCRIPT = "assets/icons/JavaScript.svg",
    TypeScript = "assets/icons/TypeScript.svg",
    Angular = "assets/icons/Angular tag.svg",
    MaterialUI = "assets/icons/Material UI.svg",
    MaterialDesign = "assets/icons/material design.svg",
    GIT = "assets/icons/GIT.svg",
    ApolloGraphQL = "assets/icons/Apollo GraphQL.svg",
    Azure_DevOps = "assets/icons/Azure_DevOps.svg",
    Jira = "assets/icons/Jira.svg",
    VSCode = "assets/icons/VSCode.svg",
    AdobeXD = "assets/icons/Adobe XD.svg",
    Figma = "assets/icons/Figma.svg",
    AdobePhotoshop = "assets/icons/Adobe Photoshop.svg",
    Swagger = "assets/icons/Swagger.svg",
}